server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'fabricode'
    password: 'password'
    url: jdbc:postgresql://localhost:6543/customer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true